project_id = "jpxogrmaxdsisvpdngok"

[functions.generate-kickoff-report]
verify_jwt = false


[functions.submit-intake]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.followup-reminder]
verify_jwt = false

[functions.generate-kickoff-core]
verify_jwt = false

[functions.generate-kickoff-email]
verify_jwt = false

[functions.generate-client-proposal]
verify_jwt = false

[functions.generate-pricing-page]
verify_jwt = false

[functions.flutterwave-checkout]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.flutterwave-verify]
verify_jwt = false
